### ISSUE TITLE
這兩題答案相反了?

### ISSUE THREAD

**Issue by insowe** [WeiChiaChang/twicon-game#10]
https://imgur.com/i3QBhbV
https://imgur.com/CP7rb3d

**Comment by WeiChiaChang** [comment]
Hello ~ @insowe 

我也有發現 XD
官方的 Medium 也有其他人提出了同樣的問題
https://medium.com/twicon/taiwan-icon-fonts-2d2c7c715047

因為資料源我是爬他們家的網站
所以等設計師確定且修正之後就會 fix 掉～

感謝回報 👍

**Comment by WeiChiaChang** [comment]
已修正～
