### ISSUE TITLE
在圖案上用Chrome檢查功能就看得出來答案

### ISSUE THREAD

**Issue by leoacevedo** [WeiChiaChang/twicon-game#17]
![作弊](https://user-images.githubusercontent.com/18398182/72554645-e278fe80-3879-11ea-862d-339de94e1918.png)

**Comment by WeiChiaChang** [comment]
Hello ~ @leoacevedo 

其實一開始有有想到但當時偷懶沒做 XD
現在有做 hash 處理了～
感謝回報 👍 

![螢幕快照 2020-01-17 下午12 33 45](https://user-images.githubusercontent.com/13506626/72584625-c16de780-3925-11ea-898c-b456aed65b4c.png)

**Comment by leoacevedo** [comment]
嗨 @WeiChiaChang，
謝謝的快速答案！
那我把這個issue關了，因為問題已經解決了。
現在我贏不了遊戲了:)
